import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import Image from "next/image";
import profile_pic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Footer from "@/components/Footer";
import Hire from "@/components/Hire";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profile_pic} alt="" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                {" "}
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 gap-4">
                <Link
                  href="/dummy.pdf"
                  className=" flex items-center bg-dark text-light p-3 px-6 rounded-lg hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  target={"_blank"}
                  download={true}
                >
                  {" "}
                  resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href=""
                  className=" flex items-center bg-light underline text-dark p-4 px-6 rounded-lg hover:bg-dark hover:text-light"
                  target={"_blank"}
                >
                  {" "}
                  Contacts
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <Hire/>
      </main>
      
    </>
  );
}
